# Generated by Django 3.0.3 on 2020-11-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job1_job2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job1',
        ),
        migrations.DeleteModel(
            name='Job2',
        ),
    ]
